name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ruby-test:
    runs-on: ubuntu-latest
    name: Ruby Tests
    strategy:
      matrix:
        rust:
          - stable
          - 1.66.0
        ruby:
          - '3.4.5'
    steps:
      - uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup override set ${{ matrix.rust }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Compile gem
        run: bundle exec rake compile

      - name: Run tests
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    strategy:
      matrix:
        ruby:
          - '3.4.5'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Rubocop
        run: bundle exec rubocop

  cargo-check:
    name: Cargo Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.66.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup override set ${{ matrix.rust }}

      - name: Run cargo check
        run: cargo check

  cargo-clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.66.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup override set ${{ matrix.rust }}

      - name: Install clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  cargo-fmt:
    name: Cargo Fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.66.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup override set ${{ matrix.rust }}

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  cargo-test:
    name: Cargo Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.66.0
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup override set ${{ matrix.rust }}

      - name: Run cargo test
        run: cargo test
